# Generated by Django 6.0.7 on 2026-07-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
