# Generated by Django 6.0.7 on 2026-07-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_remove_utilisateur_username_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
    ]
